# Central App Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-deployment
  labels:
    app: central-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-app
  template:
    metadata:
      labels:
        app: central-app
    spec:
      containers:
        - name: central-app
          image: localhost:5000/com.fombico.central
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service.default.svc.cluster.local:3306/central
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: spring.rabbitmq.host
---
# Central Service
apiVersion: v1
kind: Service
metadata:
  name: central-clusterip
spec:
  selector:
    app: central-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
